[[bond]]
source = "tpknam1qrqz0569534ajnnl6vahgfjyn73vnayh4dv6933ayn22h6u4fd0l6847fy6"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "80"

[bond.signatures]
tpknam1qrqz0569534ajnnl6vahgfjyn73vnayh4dv6933ayn22h6u4fd0l6847fy6 = "signam1qr09fmnhhzfja5c28xqaaszeg47vplyk0kaffgpm5hghmtdkuzwmuahfyjqdt8mc8x5duq3ce7hv03ggdnjrfy3geyd8mckhawkgwfqdljd7c5"


[[bond]]
source = "tpknam1qrqz0569534ajnnl6vahgfjyn73vnayh4dv6933ayn22h6u4fd0l6847fy6"
validator = "tnam1qydvhqdu2q2vrgvju2ngpt6yhrehu525pus6m28p"
amount = "20"

[bond.signatures]
tpknam1qrqz0569534ajnnl6vahgfjyn73vnayh4dv6933ayn22h6u4fd0l6847fy6 = "signam1qrpqkmqlce3mmz2prvqehv5npdsl5fw2jk2fs3f3pg8l4qkx8t0qtch6mdajjjfsxrhlqrauqgcmrqflwschnyeygzpj9qe36l24nmcv6xa6gk"
